### ISSUE TITLE
Cannot find module `fs-extra`

### ISSUE THREAD

**Issue by toebeann** [citkane/typedoc-plugin-versions#1]
In my dev environment (Windows 11, node v16.16.0), after installing this plugin I get the following error when running typedoc:

```shell
> npx typedoc
Loaded plugin typedoc-plugin-coverage
error The plugin typedoc-plugin-versions could not be loaded.
error Error: Cannot find module 'fs-extra'
Require stack:
- D:\repos\@toebean\signals\node_modules\typedoc-plugin-versions\src\index.js
...
```
This indicates to me that `fs-extra` is required to work by your plugin (and thus should probably be marked as a `dependency` in your `package.json`), so I installed it as a local `devDependency` and then ran into another issue:

```shell
> npx typedoc      
Loaded plugin typedoc-plugin-coverage
Loaded plugin typedoc-plugin-versions
TypeDoc exiting with unexpected error:
Error: ENOENT: no such file or directory, scandir
    at Object.readdirSync (node:fs:1405:3)
    at Object.getPackageDirectories (D:\repos\@toebean\signals\node_modules\typedoc-plugin-versions\src\etc\utils.js:72:31)
```

This plugin sounds great, would love to test it out locally before adding it to the CI pipeline for my TypeScript projects.

**Comment by toebeann** [comment]
Update: I found that if I explicitly set the out dir of typedoc either via CLI or `typedoc.json`, it seems to be working as expected (altho I still need to manually add `fs-extra` as a devDependency).

Possibly `readDirSync` was attempting to look at an `undefined` directory?

Perhaps in a future update it should resolve the `out` setting of `./docs` (as per typedoc defaults) when not explicitly set? 💜

**Comment by citkane** [comment]
fs-extra is already declared as a dev depency here: https://github.com/citkane/typedoc-plugin-versions/blob/fd0bf912c9a57537083b5294e8554f20c96cecd2/package.json#L36

This should not be the issue, and 'npm install' should suffice.

I will have a chance to look at this only later this week and will get back to you.

**Comment by toebeann** [comment]
If you list something as a devDependency only, then it is not installed by the dependents of your package, because devDependency means it is only needed for the development lifecycle of your package, not for it to function when distributed to consumers.

However in your package's case, it is needed for it to function. Running `npm install` after I install your plugin does not fix the issue.

So in your package's case, you would need to mark it as a normal dependency to have it automatically installed by dependents if not already.

**Comment by citkane** [comment]
Right you are.

**Comment by toebeann** [comment]
This issue is really two separate issues:
1. `fs-extra` should be a dependency
2. Plugin throws errors If `out` is not defined in config options for typedoc

I'll split the second into it's own issue so as not confuse things - my bad for not doing so in the first place

I'll whip up a PR for the fs-extra `package.json` issue as it's an easy fix :)

**Comment by citkane** [comment]
Thanks @toebeann ,
That should be good in v0.0.5, which is now published and released.

**Comment by toebeann** [comment]
Thanks, I'll test it out soon! 💜

**Comment by toebeann** [comment]
All seems perfect now, thanks for your prompt action!

One thing though, you might want to regenerate your own docs:
https://github.com/citkane/typedoc-plugin-versions/blob/519a117f19695ad5d923e0429048bfffd25bb045/typedoc.json#L14

https://citkane.github.io/typedoc-plugin-versions is redirecting to localhost ;)

**Comment by toebeann** [comment]
@citkane ^ meant to tag you in the above

**Comment by citkane** [comment]
Thanks @toebeann ,
Fixed
