### ISSUE TITLE
feat: support for mono-repositories

### ISSUE THREAD

**Issue by JulianCataldo** [citkane/typedoc-plugin-versions#22]
Hello,

Would be nice to have support for them: <https://typedoc.org/guides/monorepo/>.

But, I assume this would bring some complications, UI-wise.

Thanks.

**Comment by citkane** [comment]
Hi @JulianCataldo 

I may be misunderstanding your feature request, but the `entryPointStrategy` of TypeDoc should not matter to the plugin at all. (ie. mono-repository support could not be a feature, it is outside the scope of this plugin and should just work)

The plugin works outside of the standard TypeDoc internal document creation flow and;
- modifies the given `out` document folder
- builds file linkages and version directories
- injects the dropdown widget HTML + JS
 
If you are experiencing some trouble with it, please explain what is happening and link to a minimal reproduction repo of the issue.

**Comment by JulianCataldo** [comment]
Yes, my feat. request was not detailed enough.
I was referring to the independent packages versioning ability, whereas, typically the root package isn't bumped.

Maybe I missed it during my tests, but versioning is just for root, it stays at 0.0.0 in my case.

I think it's probably difficult to do, in all aspects (the way folders are generated with separate version, etc.).

thanks!

**Comment by citkane** [comment]
I think I understand what you are wanting to do, and yes... that is going to be a rabbit hole of complexity.
