### ISSUE TITLE
Option to generate relative symlinks instead of absolute ones?

### ISSUE THREAD

**Issue by RebeccaStevens** [citkane/typedoc-plugin-versions#29]
I'm currently run the following shell script to convert them but it would be nicer if they were just relative to begin with:

```sh
find -lname \"$PWD/docs/generated/*\" | while read link; do
  target=$(readlink $link)
  relative_target=$(realpath $target --relative-to=$link/.. --no-symlinks --canonicalize-missing)
  ln --force --symbolic --no-target-directory $relative_target $link
done
```

### Why

So symlinks committed to the gh-pages branch work on any computer they are pulled to (well, non-windows ones at least).

**Comment by citkane** [comment]
Hi Rebecca,

@RebeccaStevens - I have added that option for relative symLinks and published v0.2.4.
Let me know if it all works for you in your GH workflow.

@tintinthong - I added the option for renaming package.json from your pull request. Thanks and sorry for the long delay. 

Just a heads up to all and @toebeann ;
I will not be taking this package any further than compatibility with Typedoc v0.23. 
Typedoc v0.24 has some [breaking API changes](https://typedoc.org/guides/changelog/#v0.24.0-(2023-04-08)) which affect this and my theme, [typedoc-theme-yaf](https://citkane.github.io/typedoc-theme-yaf/dev/), which was the original reason I build the 'versions' plugin.

I am starting a new effort to build a full package with my theme, independent from Typedoc - but that will still be a while in the making.

Please feel free to fork this repo, or muck in here if you are finding it valuable.
